# Install, configure nginx & run nginx service
---
- name: Install and configure Nginx
  hosts: webservers
  become: true  # Run tasks with root privileges

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present  # Ensure Nginx is installed
      tags:
        - nginx

    - name: Copy Nginx configuration file
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx
      tags:
        - nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
